engines:
  duplication:
    enabled: true
    config:
      languages:
      - python
    exclude_paths:

  fixme:
    enabled: true
  markdownlint:
    enabled: true
  pep8:
    enabled: true
  radon:
    enabled: true
ratings:
  paths:
  - "**.py"
exclude_paths:
