falla con 1

----------------------------------
{'turist_check': '', 'debit_note': False, 'tail_text_2': '', 'tail_text_3': '', 'turist_ticket': False, 'tail_text': u'Saleman: Ornela', 'print_quantities': True, 'lines': [{'description_2': '', 'large_label': '', 'description': '', 'description_4': '', 'description_3': '', 'send_subtotal': True, 'collect_type': 'q', 'as_gross': False, 'unit_price': 81.82, 'fixed_taxes': 0, 'first_line_label': '', 'taxes_rate': 0, 'item_action': 'sale_item', 'vat_rate': 21.0, 'check_item': False, 'item_description': u'[CER289] Ecolegno Liston Roble\t13X100X4', 'quantity': 1.0}], 'tail_no_2': 0, 'cut_paper': True, 'tail_no': 1, 'print_return_attribute': False, 'related_document_2': u'OV-01471', 'origin_document': u'OV-01471', 'partner': {'name_2': '', 'document_type': 'D', 'name': u'Maximiliano Monteverde', 'address_2': u'Ituzaingo', 'address': u'Lopez Buchardo 3918', 'document_number': u'25178933', 'address_3': u'Argentina', 'responsability': 'F'}, 'electronic_answer': False, 'related_document': u'CH/EN/00448', 'current_account_automatic_pay': False, 'tail_no_3': 0}
----------------------------------
CER289 es el producto


falla la primera
----------------------------------
{'turist_check': '', 'debit_note': False, 'tail_text_2': '', 'tail_text_3': '', 'turist_ticket': False, 'tail_text': u'Saleman: Ornela', 'print_quantities': True, 'lines': [{'description_2': '', 'large_label': '', 'description': '', 'description_4': '', 'description_3': '', 'send_subtotal': True, 'collect_type': 'q', 'as_gross': False, 'unit_price': 1.0, 'fixed_taxes': 0, 'first_line_label': '', 'taxes_rate': 0, 'item_action': 'sale_item', 'vat_rate': 21.0, 'check_item': False, 'item_description': u'[CER289] Ecolegno Liston Roblce\t13X100X4', 'quantity': 1.0}], 'tail_no_2': 0, 'cut_paper': True, 'tail_no': 1, 'print_return_attribute': False, 'related_document_2': u'OV-01471', 'origin_document': u'OV-01471', 'partner': {'name_2': '', 'document_type': 'D', 'name': u'Maximiliano Monteverde', 'address_2': u'Ituzaingo', 'address': u'Lopez Buchardo 3918', 'document_number': u'25178933', 'address_3': u'Argentina', 'responsability': 'F'}, 'electronic_answer': False, 'related_document': u'CH/EN/00448', 'current_account_automatic_pay': False, 'tail_no_3': 0}
{'turist_check': '', 'debit_note': False, 'tail_text_2': '', 'tail_text_3': '', 'turist_ticket': False, 'tail_text': u'Saleman: Ornela', 'print_quantities': True, 'lines': [{'description_2': '', 'large_label': '', 'description': '', 'description_4': '', 'description_3': '', 'send_subtotal': True, 'collect_type': 'q', 'as_gross': False, 'unit_price': 1.0, 'fixed_taxes': 0, 'first_line_label': '', 'taxes_rate': 0, 'item_action': 'sale_item', 'vat_rate': 21.0, 'check_item': False, 'item_description': u'[103/15] Allegro ba\xf1era c/transferencia - FV', 'quantity': 1.0}], 'tail_no_2': 0, 'cut_paper': True, 'tail_no': 1, 'print_return_attribute': False, 'related_document_2': u'OV-01471', 'origin_document': u'OV-01471', 'partner': {'name_2': '', 'document_type': 'D', 'name': u'Maximiliano Monteverde', 'address_2': u'Ituzaingo', 'address': u'Lopez Buchardo 3918', 'document_number': u'25178933', 'address_3': u'Argentina', 'responsability': 'F'}, 'electronic_answer': False, 'related_document': u'CH/EN/00448', 'current_account_automatic_pay': False, 'tail_no_3': 0}
----------------------------------
2