{
    'turist_check': '',
    'debit_note': False,
    'tail_text_2': '',
    'tail_text_3': '',
    'turist_ticket': False,
    'tail_text': u'Saleman: Juan',
    'print_quantities': True,
    'lines': [
        {'description_2': '',
         'large_label': '',
         'description': '',
         'description_4': '',
         'description_3': '',
         'send_subtotal': True,
         'collect_type': 'q',
         'as_gross': False,
         'unit_price': 1.0,
         'fixed_taxes': 0,
         'first_line_label': '',
         'taxes_rate': 0,
         'item_action': 'sale_item',
         'vat_rate': 21.0,
         'check_item': False,
         'item_description': u'[103/15] Allegro ba\xf1era c/transferencia - FV',
         'quantity': 1.0}
    ],
    'tail_no_2': 0,
    'cut_paper': True,
    'tail_no': 1,
    'print_return_attribute': False,
    'related_document_2': '',
    'partner': {
        'name_2': '',
        'document_type': 'T',
        'name': u'a',
        'address_2': False,
        'address': False,
        'document_number': u'30550815997',
        'address_3': False,
        'responsability': 'I'
    },
    'electronic_answer': False,
    'related_document': u'No picking',
    'current_account_automatic_pay': False,
    'tail_no_3': 0
}

{'turist_check': '', 'debit_note': False, 'tail_text_2': '', 'tail_text_3': '', 'turist_ticket': False,
 'tail_text': u'Saleman: Juan', 'print_quantities': True, 'lines': [
    {'description_2': '', 'large_label': '', 'description': '', 'description_4': '', 'description_3': '',
     'send_subtotal': True, 'collect_type': 'q', 'as_gross': False, 'unit_price': 1.0, 'fixed_taxes': 0,
     'first_line_label': '', 'taxes_rate': 0, 'item_action': 'sale_item', 'vat_rate': 21.0, 'check_item': False,
     'item_description': u'[103/15] Allegro ba\xf1era c/transferencia - FV', 'quantity': 1.0}], 'tail_no_2': 0,
 'cut_paper': True, 'tail_no': 1, 'print_return_attribute': False, 'related_document_2': '',
 'partner': {'name_2': '', 'document_type': 'T', 'name': u'aqqqqqqqqq', 'address_2': False,
             'address': u'calle',
             'document_number': u'30550815997', 'address_3': False, 'responsability': 'I'}, 'electronic_answer': False,
 'related_document': u'No picking', 'current_account_automatic_pay': False, 'tail_no_3': 0}
